version: '3.8'

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200'
      - '9300'

  hireme_backend:
    build:
      context: ./backend
    volumes:
      - backend-data:/hireme_backend_volume
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - hireme_db

  hireme_db:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hireme_db
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
    ports:
      - 5432:5432

  hireme_frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    volumes:
      - frontend-data:/hireme_frontend_volume
    ports:
      - 5173:5173
    
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Africa/Lagos
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

volumes:
  db-data:
  frontend-data:
  backend-data: